export const TOGGLE_FAVORITE = "CONTENT/TOGGLE_FAVORITE";
export const GET_MOVIES = "CONTENT/SET_MOVIES";
export const GET_MOVIES_SUCCESS = "CONTENT/GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "CONTENT/GET_MOVIES_FAILURE";
